# Programming fundamental concepts: Modules and Numpy

*This assignment is not obligatory*


## Introduction

In the last tutorial we have covered the basics of Python programming, including variables, data types, and control structures. We also introduced some fundamental programming concepts such as loops and conditionals. In this tutorial we will take a closer look at functions and how to use them effectively in your code. We will not only use built-in functions but also import them from external libraries.

Throughout this tutorial, we will also focus on file handling in Python, including reading from and writing to files. This is an essential skill, since we will be working a lot with data stored in files.



### Useful tools

During coding, you will often need to look up how certain functions work. There are several useful tools to help you with this:
- The [Python documentation](https://docs.python.org/3/) or library documentation such as [NumPy](https://numpy.org/doc/stable/) and [Pandas](https://pandas.pydata.org/pandas-docs/stable/) are great resources.
- AI tools like [ChatGPT](https://chat.openai.com/) and [Copilot](https://github.com/features/copilot).
- Online forums and communities such as [Stack Overflow](https://stackoverflow.com/).


## Python packages

for this assignment we will be using the following packages:
- `numpy`: for numerical operations
- `pandas`: for data manipulation and analysis
- `os`: for interacting with the operating system

These should be installed in your Python environment. If you haven't installed them yet, you can do so using conda:

```bash
conda install numpy
```


> **Task 1:**
>
> Let's start by importing the necessary libraries.
>
> ```python
> import numpy as np
> import pandas as pd
> import os
> ```

In [17]:
import numpy as np
import pandas as pd
import os

### Numpy
Numpy (numpy documentation: https://numpy.org/doc/stable/) is one of the most popular libraries for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures. Numpy is particularly useful for handling large datasets and performing complex mathematical operations efficiently. You will be using this library extensively throughout MUDE.

We will start by creating a simple array using Numpy after which we will focus on indexing and slicing. Indexing and slicing works similarly to Python lists, but with some additional features. 

A list of useful numpy functions:

- np.array(): Create an array
- np.arange(): Create an array with a range of values
- np.zeros(): Create an array filled with zeros
- np.ones(): Create an array filled with ones
- np.eye(): Create an identity matrix
- np.reshape(): Reshape an array
- np.transpose(): Transpose an array
- np.concatenate(): Concatenate arrays
- np.split(): Split an array
- np.mean(): Compute the mean of an array
- np.sum(): Compute the sum of an array
- np.max(): Find the maximum value in an array
- np.min(): Find the minimum value in an array
- np.std(): Compute the standard deviation of an array
- np.dot(): Compute the dot product of two arrays
- np.cross(): Compute the cross product of two arrays
- np.linalg.inv(): Compute the inverse of a matrix
- np.linalg.det(): Compute the determinant of a matrix
- np.random.rand(): Generate random numbers
- np.random.randn(): Generate random numbers from a standard normal distribution


In [52]:
D1 = np.array([
    [1, 2, 3, 4, 5],
                    ])
print(D1)
D2 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 2]
                     ])
print(D2)
D3 = np.append(D2, [[10, 11, 12, 13, 14]], axis=0)
print(D3)

[[1 2 3 4 5]]
[[1 2 3 4 5]
 [6 7 8 9 2]]
[[ 1  2  3  4  5]
 [ 6  7  8  9  2]
 [10 11 12 13 14]]


> **Task 2:**
>
> We will now create a np.array with 10 rows and 3 columns. The first column is filled from 1 to 10, the second column is filled with the squares of the first column, and the third column is filled with the cubes of the first column. After we have created the array we will save it to a file.
>
> I will show you two ways to do this:
> - Starting with an empty array and filling it in a loop.
> - creating 3 separate arrays for each column and then combining them.

In [67]:
M1 = np.zeros((10, 3))
for i in range(1, 11):
    M1[i-1] = [i, i**2, i**3]
print(M1)

M2 = np.array([[1, 1, 1],
            [2, 4, 8],
            [3, 9, 27],
            [4, 16, 64],
            [5, 25, 125],
            [6, 36, 216],
            [7, 49, 343],
            [8, 64, 512],
            [9, 81, 729],
            [10, 100, 1000]
                         ])
print (M2)

np.savetxt("matrices.csv", M2, delimiter=",")


[[   1.    1.    1.]
 [   2.    4.    8.]
 [   3.    9.   27.]
 [   4.   16.   64.]
 [   5.   25.  125.]
 [   6.   36.  216.]
 [   7.   49.  343.]
 [   8.   64.  512.]
 [   9.   81.  729.]
 [  10.  100. 1000.]]
[[   1    1    1]
 [   2    4    8]
 [   3    9   27]
 [   4   16   64]
 [   5   25  125]
 [   6   36  216]
 [   7   49  343]
 [   8   64  512]
 [   9   81  729]
 [  10  100 1000]]


> **Task 3:**
>
> Now we will use some of numpy's powerful features to manipulate our data. Let's try some matrix operations. First, we will create a 3x3 matrix and perform some basic operations on it.

In [86]:
M3 = np.zeros((3, 3))
for i in range(1, 4):
    M3[i-1] = [i, i-2, i+5]
print(M3)

M3_transposed = np.transpose(M3)
print(M3_transposed)

M3_inverse = np.linalg.inv(M3)
print(M3_inverse)

M4 = np.ones((3, 3))

M3_mult = np.dot(M3, M4)
print(M3_mult)

det_M3 = np.linalg.det(M3)
print(det_M3)

M3_inverse = np.linalg.inv(M3)
print(M3_inverse)


[[ 1. -1.  6.]
 [ 2.  0.  7.]
 [ 3.  1.  8.]]
[[ 1.  2.  3.]
 [-1.  0.  1.]
 [ 6.  7.  8.]]
[[ 7.88129935e+15 -1.57625987e+16  7.88129935e+15]
 [-5.62949953e+15  1.12589991e+16 -5.62949953e+15]
 [-2.25179981e+15  4.50359963e+15 -2.25179981e+15]]
[[ 6.  6.  6.]
 [ 9.  9.  9.]
 [12. 12. 12.]]
-8.881784197001244e-16
[[ 7.88129935e+15 -1.57625987e+16  7.88129935e+15]
 [-5.62949953e+15  1.12589991e+16 -5.62949953e+15]
 [-2.25179981e+15  4.50359963e+15 -2.25179981e+15]]


## os
Now that we have our data saved in a CSV file, we can use the `os` module to interact with the file system. For example, we can check if the file exists, remove it, or rename it.

some useful os functions:
- `os.path.exists(path)`: Check if a file or directory exists
- `os.remove(path)`: Remove a file
- `os.rename(old, new)`: Rename a file or directory
- `os.listdir(path)`: List all files and directories in a directory
- `os.getcwd()`: Get the current working directory
- `os.chdir(path)`: Change the current working directory
- `os.mkdir(path)`: Create a new directory
- `os.makedirs(path)`: Create a new directory and all intermediate directories
- `os.path.join(path, *paths)`: Join one or more path components intelligently


In [69]:
os.path.exists("matrices.csv")

os.getcwd()

'c:\\Users\\Chiara\\Desktop\\MUDE\\Week_3\\PA1.3'

## Pandas

Now we will use pandas to import our newly created CSV file and perform some data analysis. We could also do this with other libraries, such as numpy, but pandas is specifically designed for data manipulation and analysis.

Some useful pandas functions include:

- `pd.read_csv()`: Read a CSV file into a DataFrame.
- `df.head()`: Display the first few rows of a DataFrame.
- `df.describe()`: Generate descriptive statistics.



> **Task 4:**
>
> Import our my_array.csv file using pandas and display the first few rows as well as the summary statistics.

In [134]:
df = pd.read_csv("matrices.csv", header=None, names=["num", "square", "cube"])

firstrows = df.head(3)

stat = df.describe()

df["sum"] = df["num"] + df["square"] + df["cube"]

DataFrame_to_np = df.to_numpy()
print(DataFrame_to_np)


[[1.00e+00 1.00e+00 1.00e+00 3.00e+00]
 [2.00e+00 4.00e+00 8.00e+00 1.40e+01]
 [3.00e+00 9.00e+00 2.70e+01 3.90e+01]
 [4.00e+00 1.60e+01 6.40e+01 8.40e+01]
 [5.00e+00 2.50e+01 1.25e+02 1.55e+02]
 [6.00e+00 3.60e+01 2.16e+02 2.58e+02]
 [7.00e+00 4.90e+01 3.43e+02 3.99e+02]
 [8.00e+00 6.40e+01 5.12e+02 5.84e+02]
 [9.00e+00 8.10e+01 7.29e+02 8.19e+02]
 [1.00e+01 1.00e+02 1.00e+03 1.11e+03]]


> By Berend Bouvy, Delft University of Technology. CC BY 4.0, more info [on the Credits page of Workbook](https://mude.citg.tudelft.nl/workbook-2025/credits.html).